return {
  { "ellisonleao/gruvbox.nvim" },
  { "craftzdog/solarized-osaka.nvim" },
  { "ray-x/aurora" },
  { "Mofiqul/vscode.nvim" },
  { "ramojus/mellifluous.nvim" },
  { "AlexvZyl/nordic.nvim" },
  { "catppuccin/nvim" },
  { "0xstepit/flow.nvim" },
  { "sainnhe/everforest" },
  { "sainnhe/sonokai" },
  { "savq/melange-nvim" },
  { "tanvirtin/monokai.nvim" },
  { "EdenEast/nightfox.nvim" },
  { "sainnhe/gruvbox-material" },
  { "fenetikm/falcon" },
  { "akinsho/horizon.nvim" },
  { "Shatur/neovim-ayu" },
  { "folke/tokyonight.nvim" },
  { "chiendo97/intellij.vim" },
  { "kvrohit/substrata.nvim" },
  { "shaunsingh/nord.nvim" },
  { "rose-pine/neovim", name = "rose-pine" },
  { "rebelot/kanagawa.nvim" },
  { "Yazeed1s/minimal.nvim" },
  { "slugbyte/lackluster.nvim" },
  { "scottmckendry/cyberdream.nvim" },
  { "nlknguyen/papercolor-theme" },
  -- Configure LazyVim to load gruvbox
  {
    "LazyVim/LazyVim",
    lazy = true,
    opts = {
      colorscheme = "vim",
    },
  },
}
